In [3]:
#Activation functions

import math

def sigmoid(x):
    return 1/(1 + math.exp(-x))

In [2]:
sigmoid(100) #[0,1] mijakayqum en arjeqnery

1.0

In [3]:
sigmoid(1)

0.7310585786300049

In [4]:
sigmoid(-45)

2.8625185805493937e-20

In [5]:
sigmoid(0.5)

0.6224593312018546

In [6]:
def tanh(x):
    return (math.exp(x) - math.exp(-x))/ (math.exp(x) + math.exp(-x))

In [12]:
tanh(100) #[-1,1] mijakayqum en arjeqnery

1.0

In [13]:
tanh(-56)

-1.0

In [14]:
def relu(x):
    return max(0,x)

In [15]:
relu(-8) #bacasakannery 0 a dardznum, drakannery nuynna toxum

0

In [16]:
relu(9)

9

In [17]:
def leaky_relu(x):
    return max(0.1*x, x)

In [20]:
leaky_relu(-100) #drakannery nuynna toxum, bacasakannery nshvac banadzevov hashvum

-10.0

In [23]:
leaky_relu(10)

10

In [4]:
#Matrix Basics

import numpy as np

revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expense = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [25]:
profit = revenue - expense
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [26]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [27]:
price_per_unit*units #yst matricneri bazmapatkman 1y 3i vra matric piti stanainq, 
# bayc numpy-um *-y broadcasting-ov a bazmapatkum anum, aysinqn 1y 3i vra matricy dardznuma 3-y 3i vra,
# avelacnuma pakas toxery arajin toxy noric grelov, aysinqn darnuma price_per_unit = np.array([[1000,400,1200], [1000,400,1200], [1000,400,1200]])

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [28]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])

In [5]:
#Loss or Cost Function

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0, 0.5])

In [36]:
#mean absolute error function

def mae(y_true, y_predicted):
    total_error = 0
    for yt,yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total error is: ", total_error)
    mae = total_error/len(y_true)
    print("MAE is: ", mae)
    return mae

In [37]:
mae(y_true, y_predicted)

Total error is:  2.5
MAE is:  0.5


0.5

In [41]:
#same using numpy

print("Total error is: ",np.sum(np.abs(y_true-y_predicted)))
print("MAE is: ",np.mean(np.abs(y_true-y_predicted)))

Total error is:  2.5
MAE is:  0.5


In [43]:
#Binary cross entropy or log loss function

np.log([0.25]) #y_predicted=1 depqum xndir enq unenalu

array([-1.38629436])

In [6]:
epsilon = 1e-15

In [7]:
y_predicted

array([1, 1, 0, 0, 1])

In [8]:
y_predicted_new = [max(i,epsilon) for i in y_predicted] #0-nery poxarinenq, 0in mot stananq vor log karananq hashvenq
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [9]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new] #1-ern enq poxarinum 1in mot tverov
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [10]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [54]:
np.log(y_predicted) #skzbnakaniny cher karanalu hashver

C:\Users\User\AppData\Local\Temp\ipykernel_14780\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [66]:
-np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [11]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [12]:
log_loss(y_true, y_predicted)

17.2696280766844